---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 13/10/2024
---

_cn.HudModule = "HudModule";
loadClass(_cn.HudModule)

--- Imports ---
_a.ApplicationScope()
_a.AModule()
---@class HudModule : Module
local HudModule = extends("HudModule", "Module");

function HudModule.new()
    ---@type HudModule
    local self = initMetatable(HudModule);

    return self;
end

function HudModule:onLoad()
    self.huds = {};
    self.hudsHide = {};

    DisplayCash(true);

    self:showHud(Enum.HudReference.HUD_CASH);
    self:showHud(Enum.HudReference.HUD_MP_CASH);
end

function HudModule:onStart()
    ---@type ThreadTimer
    self.threadTick = _c.ThreadTimer.new(function()
        self:drawHud();
    end, 0);
    self.threadTick:run();
end

function HudModule:onStop()
    self.threadTick:kill();
end

function HudModule:showHud(hudReference)
    self.huds[#self.huds + 1] = hudReference;
    self:addHudCash(hudReference);
end

---@private
function HudModule:addHudCash(hudReference)
    if (hudReference == Enum.HudReference.HUD_MP_CASH) then
        DisplayCash(true);
    end
end

function HudModule:hideHud(hudReference)
    for i = 1, #self.huds do
        if self.huds[i] == hudReference then
            table.remove(self.huds, i);
            break ;
        end
    end

    self:removeHudCash(hudReference);
end

---@private
function HudModule:removeHudCash(hudReference)
    if (hudReference == Enum.HudReference.HUD_MP_CASH) then
        DisplayCash(false);
    end
end

function HudModule:forceHideHud(hudReference)
    self.hudsHide[#self.hudsHide + 1] = hudReference;
end

function HudModule:forceShowHud(hudReference)
    for i = 1, #self.hudsHide do
        if self.hudsHide[i] == hudReference then
            table.remove(self.hudsHide, i);
            break ;
        end
    end
end

function HudModule:changeMoneyAmount(amount)
    StatSetInt('MP0_WALLET_BALANCE', amount, true);
end

function HudModule:drawHud()
    for i = 1, #self.huds do
        ShowHudComponentThisFrame(self.huds[i]);
        if (self.huds[i] == Enum.HudReference.HUD_MP_CASH) then
            SetMultiplayerWalletCash();
        end
    end

    for i = 1, #self.hudsHide do
        HideHudComponentThisFrame(self.hudsHide[i]);
        if (self.huds[i] == Enum.HudReference.HUD_MP_CASH) then
            RemoveMultiplayerHudCash();
        end
    end
end

_c.HudModule = HudModule;
classloaded(_cn.HudModule)