---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 06/10/2024
---

_cn.MasterGame = "MasterGame";
loadClass(_cn.MasterGame)

--- Imports ---

import(_cn.Nui)

_a.ApplicationScope()
_a.AModule()
---@class MasterGame : Module
local MasterGame = extends("MasterGame", "Module");

_a.Inject(_c.Nui)
---@type Nui
MasterGame.nui = nil

function MasterGame.new()
    ---@type MasterGame
    local self = initMetatable(MasterGame);

    self.playerEnterInVehicle = _c.Signal.new();

    Ats.thread(function()
        self.client = getSingleton(_c.Client);

        AddEventHandler('gameEventTriggered', function(name, args)

            if name == "CEventNetworkPlayerDeactivatedSpecialAbility" then
                return ;
            end

            print('game event ' .. name .. ' (' .. json.encode(args) .. ')')
            if name == "CEventNetworkPlayerEnteredVehicle" then
                local vehicleIdLocal = args[2];
                local vehiclePlayerIsIn = GetVehiclePedIsIn(PlayerPedId(), false);
                if vehicleIdLocal == vehiclePlayerIsIn then
                    self.playerEnterInVehicle:fire(self.client:getPed():getVehicleIsIn());
                end
            end
        end)
    end)

    return self;
end

_a.OnNuiEvent({ nuiName = "startGame" })
function MasterGame:ready()
    self:goToGame();
    local client = getSingleton(_c.Client);
    client.clientReady:fire();
    self.nui:setFocus(false, false);
end

function MasterGame:goToGame()
end

function MasterGame:goToPause()
end

function MasterGame:goToStart()
end

_c.MasterGame = MasterGame;
classloaded(_cn.MasterGame)

