---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 05/10/2024
---

_cn.Color = "Color";
loadClass(_cn.Color)

--- Imports ---

---@class Color : BaseObject
local Color = class("Color");

function Color.new(r, g, b, a)
    ---@type Color
    local self = initMetatable(Color);

    self.r = r;
    self.g = g;
    self.b = b;
    self.a = a;

    return self;
end

_c.Color = Color;
classloaded(_cn.Color)