---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 05/10/2024
---

_cn.Marker = "Marker";
loadClass(_cn.Marker)

--- Imports ---

---@class Marker : DrawableElement
local Marker = extends(_cn.Marker, _cn.DrawableElement);

local index = 0;

---@param marker number
---@param position Vector3
---@param scale Vector3
---@param color Color
function Marker.new(marker, position, distance, scale, color)
    ---@type Marker
    local self = initMetatable(Marker);

    self:super(color, position, distance or 10.0);

    self.marker = marker;
    self.position = position;
    self.scale = scale;

    index = index + 1;

    self.index = index;

    return self;
end

function Marker:draw()
    local coords <const> = self:getCoords();
    DrawMarker(self.marker,
            coords.x, coords.y, coords.z,
            0, 0, 0, 0, 0, 0,
            self.scale.x, self.scale.y, self.scale.z,
            self.color.r, self.color.g, self.color.b, self.color.a,
            false, false,
            2,
            false, nil, nil, false);
end

_c.Marker = Marker;
classloaded(_cn.Marker)
