---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 05/10/2024
---

_cn.Text3D = "Text3D";
loadClass(_cn.Text3D)

--- Imports ---

---@class Text3D : DrawableElement
local Text3D = extends("Text3D", "DrawableElement");

---@param text string
---@param scale number
---@param x number
---@param y number
---@param z number
function Text3D.new(text, scale, x, y, z, distance, color)
    ---@type Text3D
    local self = initMetatable(Text3D);

    self:super(color, vector3(x or 0, y or 0, z or 0), distance or 10.0);

    self.text = text;
    self.scale = scale;
    self.backgroundColor = nil;

    return self;
end

function Text3D:drawBackground(color)
    self.backgroundColor = color or _c.Color.new(0, 0, 0, 255);
end

function Text3D:draw()
    local coords <const> = self:getCoords();

    local distanceFromPlayer = #(GetEntityCoords(PlayerPedId()) - coords)
    if distanceFromPlayer > self.distance then
        return
    end

    local text, scl_factor, x, y, z = self.text, self.scale, coords.x, coords.y, coords.z

    scl_factor = scl_factor or 1.0
    local onScreen, _x, _y = World3dToScreen2d(x, y, z)
    local p = GetGameplayCamCoords()
    local distance = GetDistanceBetweenCoords(p.x, p.y, p.z, x, y, z, 1)
    local scale = (1 / distance) * 2
    local fov = (1 / GetGameplayCamFov()) * 100
    scale = scale * fov * scl_factor

    if onScreen then
        SetTextFont(0)
        SetTextScale(0.0, scale)
        SetTextCentre(true)

        BeginTextCommandWidth("STRING")
        AddTextComponentSubstringPlayerName(text)
        local textWidth = EndTextCommandGetWidth(true) + 0.01

        BeginTextCommandLineCount("STRING")
        AddTextComponentSubstringPlayerName(text)
        local lineCount = EndTextCommandLineCount(0.0, 0.0)
        local textHeight = (0.08 * scale) * lineCount + 0.01

        SetDrawOrigin(x, y, z + 0.4, 0)

        if self.backgroundColor then
            DrawRect(0.0, textHeight / 2, textWidth, textHeight, self.backgroundColor.r, self.backgroundColor.g,
                    self.backgroundColor.b, self.backgroundColor.a)
        end

        SetTextScale(0.0, scale)
        SetTextFont(0)
        SetTextProportional(1)
        SetTextColour(self.color.r or 255, self.color.g or 255, self.color.b or 255, self.color.a or 255)
        SetTextDropshadow(0, 0, 0, 0, 255)
        SetTextEdge(2, 0, 0, 0, 150)
        SetTextDropShadow()
        SetTextOutline()
        SetTextEntry("STRING")
        SetTextCentre(1)
        AddTextComponentString(text)

        EndTextCommandDisplayText(0.0, (textHeight / 2) - (0.035 * scale))

        ClearDrawOrigin()
    end
end

_c.Text3D = Text3D;
classloaded(_cn.Text3D)
