---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 12/10/2024
---

_cn.Player = "Player";
loadClass(_cn.Player)

--- Imports ---

---@class Player : BaseObject
local Player = class("Player");

function Player.new()
    ---@type Player
    local self = initMetatable(Player);

    self.data = _c.Map.new();
    
    return self;
end

function Player:setData(key, value)
    self.data:put(key, value);
end

function Player:getData(key)
    return self.data:get(key);
end

_c.Player = Player;
classloaded(_cn.Player)