---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:18
---

_cn.Mock = "Mock";
loadClass(_cn.Mock)

--- Imports ---

---@class Mock : BaseObject
local Mock = class("Mock");

function Mock.new()
    ---@type Mock
    local self = initMetatable(Mock);



	self.method = nil;
	self.returnValue = nil;
	self.doNothing = nil;

    return self;
end

function Mock:when(obj, methodName)
	self.obj = obj;
	local method = self.obj[methodName];

	if method == nil then
		error("Method " .. methodName .. " not found in object");
	end

	self.method = method;

	if(self.doNothing) then
		self.obj[methodName] = function(...)

		end
		return;
	end

	self.obj[methodName] = function(...)
		return self.returnValue;
	end
end

function Mock:verify()
	if self.method == nil then
		error("Method not set");
	end
end

_c.Mock = Mock;
classloaded(_cn.Mock)