---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jokir.
--- DateTime: 14/10/2024 19:15
---

Enum.SoundReference = {
    ["MP_MISSION_COUNTDOWN_SOUNDSET_10s"] = { SOUND_SET_NAME = "MP_MISSION_COUNTDOWN_SOUNDSET", SOUND_NAME = "10s", DESCRIPTION = "10 second countdown timer" },
    ["HUD_AWARDS_BASE_JUMP_PASSED"] = { SOUND_SET_NAME = "MP_MISSION_COUNTDOWN_SOUNDSET", SOUND_NAME = "BASE_JUMP_PASSED", DESCRIPTION = "Sucess mission" }
}