---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 15/10/2024
---

_cn.AZone = "AZone";
loadClass(_cn.AZone)

--- Imports ---

---@class AZone : Annotation
local AZone = extends(_cn.AZone, _cn.Annotation);

function AZone.new()
    ---@type AZone
    local self = initMetatable(AZone);

    return self;
end

function AZone:onInstantiate(object, attr)
    local zoneModule = getSingleton(_c.ZoneModule);

end

_a.AZone = annotation(_cn.AZone, AZone)
_c.AZone = AZone;
classloaded(_cn.AZone)