---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 15/10/2024
---

_cn.CircleZone = "CircleZone";
loadClass(_cn.CircleZone)

--- Imports ---

---@class CircleZone : Zone
local CircleZone = extends(_cn.CircleZone, _cn.Zone);

function CircleZone.new(position, radius)
    ---@type CircleZone
    local self = initMetatable(CircleZone);

    return self;
end

function CircleZone:getPosition()
    return self.position;
end

function CircleZone:setPosition(position)
    self.position = position;
end

function CircleZone:getRadius()
    return self.radius;
end

function CircleZone:setRadius(radius)
    self.radius = radius;
end

---@param ped Ped
function CircleZone:isPedInZone(ped)
    local distance = #(ped:getCoords() - self.position);
    return distance <= self.radius;
end

_c.CircleZone = CircleZone;
classloaded(_cn.CircleZone)