---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 15/10/2024
---

_cn.ZoneModule = "ZoneModule";
loadClass(_cn.ZoneModule)

--- Imports ---
_a.ApplicationScope()
_a.AModule()
---@class ZoneModule : Module
local ZoneModule = extends("ZoneModule", "Module");

function ZoneModule.new()
    ---@type ZoneModule
    local self = initMetatable(ZoneModule);

    self.zones = _c.Map.new();

    self.zoneAnalysed = _c.List.new();

    return self;
end

function ZoneModule:registerZone(zone)
    self.zones:push(zone);
end

function ZoneModule:analyseZone(zones)
    self.zoneAnalysed:push(zones);
end

function ZoneModule:stopAnalyseZone(zones)
    self.zoneAnalysed:removeElement(zones);
end

function ZoneModule:registerZone(zone)
    self.zones:push(zone);
end

---@param peds Ped[]
function ZoneModule:analyse(peds)
    for i = 1, self.zoneAnalysed:asTable() do
        ---@type Zone
        local zone = self.zoneAnalysed:get(i);

        for j = 1, #peds do
            local ped = peds[j];
            if zone:isPedInZone(ped) then
                zone:onPlayerEnter(ped);
            else
                zone:onPlayerExit(ped);
            end
        end
    end
end

_c.ZoneModule = ZoneModule;
classloaded(_cn.ZoneModule)