---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 15/10/2024
---

_cn.Zone = "Zone";
loadClass(_cn.Zone)

--- Imports ---

---@class Zone : BaseObject
local Zone = class("Zone");

function Zone.new()
    ---@type Zone
    local self = initMetatable(Zone);

    self.entered = _c.Signal.new();
    self.exited = _c.Signal.new();

    self.zones = _c.List.new();

    self.isInZone = false;

    return self;
end

function Zone:registerZone(zone)
    self.zones:push(zone);
end

function Zone:onPlayerEnter(player)
    if self.isInZone then
        return
    end
    self.isInZone = true;
    self.entered:fire(player, self);
    self:addChildZoneToZoneManager();
end

function Zone:onPlayerExit(player)
    if not self.isInZone then
        return
    end
    self.isInZone = false;
    self.exited:fire(player, self);
    self:removeChildZoneFromZoneManager();
end

function Zone:isPedInZone(ped)
    return false;
end

function Zone:addChildZoneToZoneManager()
    local zoneModule = getSingleton(_c.ZoneModule);
    zoneModule:analyseZone(self.zones);
end

function Zone:removeChildZoneFromZoneManager()
    local zoneModule = getSingleton(_c.ZoneModule);
    zoneModule:stopAnalyseZone(zone);
end

_c.Zone = Zone;
classloaded(_cn.Zone)