---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:18
---

_cn.Observer = "Observer";
loadClass(_cn.Observer)

--- Imports ---

---@class Observer : BaseObject
local Observer = class("Observer");

function Observer.new()
    ---@type Observer
    local self = initMetatable(Observer);

    self._next = nil;
    self._error = nil;
    self._complete = nil;

    return self;
end

function Observer:next(value)
    self._next(value);
end

function Observer:error(value)
    self._next(value);
end

function Observer:complete()
    self._complete();
end

function Observer:finalize()

end

_c.Observer = Observer;
classloaded(_cn.Observer)