---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jokir.
--- DateTime: 10/10/2024 23:58
---

local en = {
    ["world"] = "World",
    ["welcome"] = "Welcome to Amnesty",
    ["goodbye"] = "Goodbye",
    ["thanks"] = "Thanks",
    ["bye"] = "Bye",
    ["yes"] = "Yes",
    ["no"] = "No",
    ["ok"] = "Ok",
    ["cancel"] = "Cancel",
    ["error"] = "Error",
    ["success"] = "Success",
    ["info"] = "Info",
    ["warning"] = "Warning",
    ["question"] = "Question",
    ["confirm"] = "Confirm",
    ["accept"] = "Accept",
    ["refuse"] = "Refuse",
    ["close"] = "Close",
    ["open"] = "Open",
    ["back"] = "Back",
    ["next"] = "Next",
    ["finish"] = "Finish",
    ["loading"] = "Loading",
    ["loading_text"] = "Please wait...",
}

Locale["en"] = en
