---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jokir.
--- DateTime: 29/09/2024 19:41
---

Enum.ChatFormatting = {
    BOLD = "^*",
    ITALIC = "^_",
    STRIKETHROUGH = "^~",
    UNDERLINE = "^u",
    STRIKETHROUGH = "^=",
    BOLD_UNDERLINE_STRIKETHROUGH = "^*^=",
    RESET = "^r",
}

_chf = {
    B = Enum.ChatFormatting.BOLD,
    I = Enum.ChatFormatting.ITALIC,
    S = Enum.ChatFormatting.STRIKETHROUGH,
    U = Enum.ChatFormatting.UNDERLINE,
    ST = Enum.ChatFormatting.STRIKETHROUGH,
    BUS = Enum.ChatFormatting.BOLD_UNDERLINE_STRIKETHROUGH,
    R = Enum.ChatFormatting.RESET,
}