---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Abou.
--- DateTime: 21/12/2023 01:18
---

_cn.Component = "Component";
loadClass(_cn.Component)

--- Imports ---

---@class Component : BaseObject
local Component = class("Component");

function Component.new()
    ---@type Component
    local self = initMetatable(Component);
    ---@type Entity
    self.entity = nil;

    return self;
end

function Component:onAdded()
end

function Component:onRemoved()
end

function Component:onUpdate()
end

_c.Component = Component;
classloaded(_cn.Component)