---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 12/10/2024
---

_cn.EntityService = "EntityService";
loadClass(_cn.EntityService)

--- Imports ---
import(_cn.AClient)

---@class EntityService : BaseObject
local EntityService = class("EntityService");

function EntityService.new()
    ---@type EntityService
    local self = initMetatable(EntityService);

    self.entities = _c.Map.new();

    return self;
end

_a.AClient()
function EntityService:listenDamage()
    AddEventHandler("entityDamaged", function(entity, attacker, weapon, damage)
        ---@type Entity
        local ent = self.entities:get(entity)
        if ent then
            ent.entityDamaged:fire(attacker, weapon, damage)
            print("Entity damaged: " .. entity)
            if (ent:getHealth() <= 0) then
                self.entities:remove(entity.id .. "")
                ent.onDeath:fire(attacker, weapon, damage)
            end
        end
    end)
end

function EntityService:register(entity)
    self.entities:put(entity.id .. "", entity);
end

function EntityService:unregister(entity)
    self.entities:removeElement(entity);
end

_c.EntityService = EntityService;
classloaded(_cn.EntityService)
singleton(_cn.EntityService)