---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 14/10/2024
---

_cn.SoundGtaModule = "SoundGtaModule";
loadClass(_cn.SoundGtaModule)

--- Imports ---
_a.ApplicationScope()
_a.AModule()
---@class SoundGtaModule : Module
local SoundGtaModule = extends("SoundGtaModule", "Module");

function SoundGtaModule.new()
    ---@type SoundGtaModule
    local self = initMetatable(SoundGtaModule);

    return self;
end

_c.SoundGtaModule = SoundGtaModule;
classloaded(_cn.SoundGtaModule)