---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 05/10/2024
---

_cn.ThreadTimer = "ThreadTimer";
loadClass(_cn.ThreadTimer)

--- Imports ---
---
---@class ThreadTimer : Thread
local ThreadTimer = extends(_cn.ThreadTimer, _cn.Thread);

function ThreadTimer.new(cb, time)
    ---@type ThreadTimer
    local self = initMetatable(ThreadTimer);

    self.cb = cb;
    self.time = time or 0;

    return self;
end

function ThreadTimer:run()
    self.__parent__.run(self);
    self.isRunning = true;
    Citizen.CreateThread(function()
        while self.isRunning do
            self.cb(self);
            Citizen.Wait(self.time);
        end
    end)
end

_c.ThreadTimer = ThreadTimer;
classloaded(_cn.ThreadTimer);