---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 03/10/2024
---

_cn.Game = "Game";
loadClass(_cn.Game)

--- Imports ---
_a.ApplicationScope()
---@class Game : Module
local Game = class("Game");

function Game.new()
    ---@type Game
    local self = initMetatable(Game);

    return self;
end

function Game:pause()
    Log.info("Game paused")
end

function Game:resume()
    Log.info("Game resumed")
end

function Game:load()
    Log.info("Game loaded")
end

_c.Game = Game;
classloaded(_cn.Game)