---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:18
---

_cn.VehicleController = "VehicleController";
loadClass(_cn.VehicleController)

--- Imports ---

import(_cn.ApplicationScope)
import(_cn.Inject)
import(_cn.Client)

---@type InputService
local Input = import(_cn.InputService);

import(_cn.OnKeyUp)

_a.ApplicationScope()
---@class VehicleController : BaseObject
local VehicleController = class("VehicleController");

_a.Inject(_c.Client)
---@type Client
VehicleController.client = nil;

function VehicleController.new()
    ---@type VehicleController
    local self = initMetatable(VehicleController);
    return self;
end

_a.OnKeyUp({ keyCode = Interface.keyCode.SPACE, name = "Test" })
function VehicleController:test()
    print("Test key up")
end

_a.OnKeyDown({ keyCode = Interface.keyCode.SPACE, name = "Test" })
function VehicleController:test2()
    print("Test key down")
end

_c.VehicleController = VehicleController;
classloaded(_cn.VehicleController)