---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 12/10/2024
---

_cn.AServer = "AServer";
loadClass(_cn.AServer)

--- Imports ---

---@class AServer : Annotation
local AServer = extends(_cn.AServer, _cn.Annotation);

function AServer.new()
    ---@type AServer
    local self = initMetatable(AServer);

    return self;
end

function AServer:onInstantiate(object, attr)
    if Ats.isClient() then
        object[attr] = function()
            Log.error("Method " .. attr .. " is not available on client side");
        end
    end
end

function AServer:onValueChange(object, attr)
end

_a.AServer = annotation(_cn.AServer, AServer)
_c.AServer = AServer;
classloaded(_cn.AServer)