---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jokir.
--- DateTime: 04/10/2024 10:50
---

Enum.ActionType = {
    KeyUp = "KeyUp",
    KeyDown = "KeyDown",
    KeyHold = "KeyHold",
    MouseUp = "MouseUp",
    MouseDown = "MouseDown",
    MouseHold = "MouseHold",
}