---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 10/10/2024
---

_cn.Terminal = "Terminal";
loadClass(_cn.Terminal)

--- Imports ---

---@class Terminal : BaseObject
local Terminal = class("Terminal");

function Terminal.new()
    ---@type Terminal
    local self = initMetatable(Terminal);

    self.isOpen = false;

    ---@type Nui
    self.nui = getSingleton(_c.Nui);

    return self;
end

_a.OnNuiEvent({ nuiName = "executeCommand" })
function Terminal:onReceivedCommand(data)
    if data.command == "close" then
        self.isOpen = false;
    end
end

_a.OnNuiEvent({ nuiName = "closeTerminal" })
function Terminal:onCloseTerminal()
    self.nui:setFocus(false, false);
    self.isOpen = false;
end

_a.OnKeyUp({ keyCode = Interface.keyCode.F3, name = "Test" })
function Terminal:toogle()
    self.isOpen = not self.isOpen;

    local nui = getSingleton(_c.Nui);
    if self.isOpen then
        nui:setFocus(true, false);
    else
        nui:setFocus(false, false);
    end

    nui:send("toggleTerminal", self.isOpen);
end

function Terminal:sendMessage(message)

end

_c.Terminal = Terminal;
classloaded(_cn.Terminal)
singleton(_cn.Terminal)
