---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 05/10/2024
---

_cn.Skin = "Skin";
loadClass(_cn.Skin)

--- Imports ---

---@class Skin : BaseObject
local Skin = class("Skin");

function Skin.new()
    ---@type Skin
    local self = initMetatable(Skin);

    self.sex = 0
    self.face = 0
    self.skin = 0
    self.age_1 = 0
    self.age_2 = 0
    self.beard_1 = 0
    self.beard_2 = 0
    self.beard_3 = 0
    self.beard_4 = 0
    self.hair_1 = 0
    self.hair_2 = 0
    self.hair_color_1 = 0
    self.hair_color_2 = 0
    self.eyebrows_1 = 0
    self.eyebrows_2 = 0
    self.eyebrows_3 = 0
    self.eyebrows_4 = 0
    self.makeup_1 = 0
    self.makeup_2 = 0
    self.makeup_3 = 0
    self.makeup_4 = 0
    self.lipstick_1 = 0
    self.lipstick_2 = 0
    self.lipstick_3 = 0
    self.lipstick_4 = 0
    self.ears_1 = 0
    self.ears_2 = 0
    self.tshirt_1 = 0
    self.tshirt_2 = 0
    self.torso_1 = 0
    self.torso_2 = 0
    self.decals_1 = 0
    self.decals_2 = 0
    self.arms = 0
    self.pants_1 = 0
    self.pants_2 = 0
    self.shoes_1 = 0
    self.shoes_2 = 0
    self.mask_1 = 0
    self.mask_2 = 0
    self.bproof_1 = 0
    self.bproof_2 = 0
    self.chain_1 = 0
    self.chain_2 = 0
    self.bags_1 = 0
    self.bags_2 = 0
    self.helmet_1 = 0
    self.helmet_2 = 0
    self.glasses_1 = 0
    self.glasses_2 = 0

    return self;
end

_c.Skin = Skin;
classloaded(_cn.Skin)