---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:18
---

_cn.KvpCache = "KvpCache";
loadClass(_cn.KvpCache)

--- Imports ---

---@class KvpCache : Cache
local KvpCache = extends(_cn.KvpCache, _cn.Cache);

function KvpCache.new()
    ---@type KvpCache
    local self = initMetatable(KvpCache);

    return self;
end

function KvpCache:set(key, value)
    local json = json.encode(value);
    Log.debug("Set KVP: %s v: %s", key, json);

    SetResourceKvp(key, json);
end

function KvpCache:get(key)
    Log.debug("Get KVP: %s", key);
    local data = GetResourceKvpString(key);
    return data and json.decode(data) or nil;
end

function KvpCache:has(key)
    return GetResourceKvpString(key) ~= nil;
end

_c.KvpCache = KvpCache;
classloaded(_cn.KvpCache)